-- 1. Movies Table
create table if not exists movies (
  id bigint generated by default as identity primary key,
  tmdb_id int unique not null,
  title text not null,
  original_title text,
  overview text,
  poster_path text,
  backdrop_path text,
  release_date date,
  vote_average numeric,
  popularity numeric,
  is_published boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Check and add missing columns if table exists but column doesn't
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'tmdb_id') then
    alter table movies add column tmdb_id int unique;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'original_title') then
    alter table movies add column original_title text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'overview') then
    alter table movies add column overview text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'poster_path') then
    alter table movies add column poster_path text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'backdrop_path') then
    alter table movies add column backdrop_path text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'release_date') then
    alter table movies add column release_date date;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'vote_average') then
    alter table movies add column vote_average numeric;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'popularity') then
    alter table movies add column popularity numeric;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'is_published') then
    alter table movies add column is_published boolean default true;
  end if;
end $$;

-- Check and add missing columns for embed_links
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'embed_links' and column_name = 'media_type') then
    alter table embed_links add column media_type text check (media_type in ('movie', 'episode'));
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'embed_links' and column_name = 'movie_id') then
    alter table embed_links add column movie_id bigint references movies(id) on delete cascade;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'embed_links' and column_name = 'episode_id') then
    alter table embed_links add column episode_id bigint references episodes(id) on delete cascade;
  end if;
end $$;

-- 2. Series Table
create table if not exists tv_series (
  id bigint generated by default as identity primary key,
  tmdb_id int unique not null,
  name text not null,
  original_name text,
  overview text,
  poster_path text,
  backdrop_path text,
  first_air_date date,
  vote_average numeric,
  popularity numeric,
  is_published boolean default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. Seasons Table
create table if not exists seasons (
  id bigint generated by default as identity primary key,
  series_id bigint references tv_series(id) on delete cascade,
  tmdb_id int,
  season_number int not null,
  name text,
  overview text,
  poster_path text,
  air_date date,
  created_at timestamp with time zone default now(),
  unique(series_id, season_number)
);

-- 4. Episodes Table
create table if not exists episodes (
  id bigint generated by default as identity primary key,
  season_id bigint references seasons(id) on delete cascade,
  series_id bigint references tv_series(id) on delete cascade,
  tmdb_id int,
  episode_number int not null,
  name text,
  overview text,
  still_path text,
  air_date date,
  vote_average numeric,
  created_at timestamp with time zone default now(),
  unique(season_id, episode_number)
);

-- 5. Embed Links Table (Polymorphic association for Movies and Episodes)
create table if not exists embed_links (
  id bigint generated by default as identity primary key,
  movie_id bigint references movies(id) on delete cascade,
  episode_id bigint references episodes(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'episode')),
  server_name text, -- e.g., 'VidSrc', 'SuperEmbed'
  url text not null,
  quality text default 'HD',
  is_active boolean default true,
  created_at timestamp with time zone default now(),
  -- Ensure link belongs to either a movie or an episode, not both or neither
  constraint check_link_target check (
    (media_type = 'movie' and movie_id is not null and episode_id is null) or
    (media_type = 'episode' and episode_id is not null and movie_id is null)
  )
);

-- 6. Genres Table
create table if not exists genres (
  id bigint generated by default as identity primary key,
  tmdb_id int unique not null,
  name text not null
);

-- 7. Media Genres Junction Table
create table if not exists media_genres (
  id bigint generated by default as identity primary key,
  movie_id bigint references movies(id) on delete cascade,
  series_id bigint references tv_series(id) on delete cascade,
  genre_id bigint references genres(id) on delete cascade,
  unique(movie_id, genre_id),
  unique(series_id, genre_id)
);

-- 8. Subtitles Table (Bonus)
create table if not exists subtitles (
  id bigint generated by default as identity primary key,
  movie_id bigint references movies(id) on delete cascade,
  episode_id bigint references episodes(id) on delete cascade,
  language text default 'ar',
  url text not null,
  format text default 'vtt',
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table movies enable row level security;
alter table tv_series enable row level security;
alter table seasons enable row level security;
alter table episodes enable row level security;
alter table embed_links enable row level security;
alter table genres enable row level security;
alter table media_genres enable row level security;
alter table subtitles enable row level security;

-- Public Read Access Policies
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Public movies are viewable by everyone') then
    create policy "Public movies are viewable by everyone" on movies for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public series are viewable by everyone') then
    create policy "Public series are viewable by everyone" on tv_series for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public seasons are viewable by everyone') then
    create policy "Public seasons are viewable by everyone" on seasons for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public episodes are viewable by everyone') then
    create policy "Public episodes are viewable by everyone" on episodes for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public embed_links are viewable by everyone') then
    create policy "Public embed_links are viewable by everyone" on embed_links for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public genres are viewable by everyone') then
    create policy "Public genres are viewable by everyone" on genres for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public media_genres are viewable by everyone') then
    create policy "Public media_genres are viewable by everyone" on media_genres for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Public subtitles are viewable by everyone') then
    create policy "Public subtitles are viewable by everyone" on subtitles for select using (true);
  end if;
end $$;

-- Admin Write Access Policies
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert movies') then
    create policy "Authenticated users can insert movies" on movies for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can update movies') then
    create policy "Authenticated users can update movies" on movies for update to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can delete movies') then
    create policy "Authenticated users can delete movies" on movies for delete to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert series') then
    create policy "Authenticated users can insert series" on tv_series for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can update series') then
    create policy "Authenticated users can update series" on tv_series for update to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert seasons') then
    create policy "Authenticated users can insert seasons" on seasons for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert episodes') then
    create policy "Authenticated users can insert episodes" on episodes for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert embed_links') then
    create policy "Authenticated users can insert embed_links" on embed_links for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert media_genres') then
    create policy "Authenticated users can insert media_genres" on media_genres for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Authenticated users can insert genres') then
    create policy "Authenticated users can insert genres" on genres for insert to authenticated with check (true);
  end if;
end $$;
