
-- Games
ALTER TABLE games ADD COLUMN IF NOT EXISTS poster_path TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS overview TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS release_date DATE;
ALTER TABLE games ADD COLUMN IF NOT EXISTS download_urls JSONB DEFAULT '{}'::JSONB;
ALTER TABLE games ADD COLUMN IF NOT EXISTS download_url TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE games ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS rating NUMERIC;
ALTER TABLE games ADD COLUMN IF NOT EXISTS category TEXT;

-- Software
ALTER TABLE software ADD COLUMN IF NOT EXISTS poster_path TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS overview TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS release_date DATE;
ALTER TABLE software ADD COLUMN IF NOT EXISTS download_urls JSONB DEFAULT '{}'::JSONB;
ALTER TABLE software ADD COLUMN IF NOT EXISTS download_url TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE software ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS rating NUMERIC;
ALTER TABLE software ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE software ADD COLUMN IF NOT EXISTS release_year INTEGER;
ALTER TABLE software ADD COLUMN IF NOT EXISTS poster_url TEXT;
ALTER TABLE software ADD COLUMN IF NOT EXISTS description TEXT;
