ALTER TABLE tv_series ALTER COLUMN name DROP NOT NULL;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS embed_links JSONB DEFAULT '{}'::JSONB;
CREATE TABLE IF NOT EXISTS embed_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    priority INTEGER DEFAULT 3,
    response_time_ms INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    last_checked TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS link_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT,
    url TEXT,
    status_code INTEGER,
    response_time_ms INTEGER,
    checked_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE embed_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_checks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view embed_sources" ON embed_sources;
CREATE POLICY "Public can view embed_sources" ON embed_sources FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public can view link_checks" ON link_checks;
CREATE POLICY "Public can view link_checks" ON link_checks FOR SELECT USING (true);
NOTIFY pgrst, 'reload schema';