
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS overview TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS poster_path TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS backdrop_path TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS rating_color TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS genres JSONB;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS first_air_date DATE;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS trailer_url TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS arabic_title TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS embed_links JSONB DEFAULT '{}'::JSONB;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS subtitle_urls JSONB DEFAULT '{}'::JSONB;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS last_checked TIMESTAMPTZ;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
