
-- Fix TV Series
ALTER TABLE tv_series ALTER COLUMN name DROP NOT NULL;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS title TEXT; -- Should already exist, but safe to check

-- Fix Episodes
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS embed_links JSONB DEFAULT '{}'::JSONB;

-- Create embed_sources
CREATE TABLE IF NOT EXISTS embed_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    priority INTEGER DEFAULT 3,
    response_time_ms INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    last_checked TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create link_checks
CREATE TABLE IF NOT EXISTS link_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name TEXT REFERENCES embed_sources(name) ON DELETE CASCADE,
    url TEXT,
    status_code INTEGER,
    response_time_ms INTEGER,
    checked_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE embed_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_checks ENABLE ROW LEVEL SECURITY;

-- Public read policies
CREATE POLICY "Public can view embed_sources" ON embed_sources FOR SELECT USING (true);
CREATE POLICY "Public can view link_checks" ON link_checks FOR SELECT USING (true);

-- Reload schema
NOTIFY pgrst, 'reload schema';
