
ALTER TABLE anime ADD COLUMN IF NOT EXISTS backdrop_path TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS trailer_url TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS rating NUMERIC;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS studios JSONB;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS synopsis TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS episodes INTEGER;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS duration TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS season TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS broadcast TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE anime ADD COLUMN IF NOT EXISTS genres JSONB;

NOTIFY pgrst, 'reload schema';
