-- Enable pg_trgm for fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create categories table if not exists
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Make columns robust in movies
ALTER TABLE movies ALTER COLUMN title SET DEFAULT 'Untitled';
ALTER TABLE movies ALTER COLUMN overview DROP NOT NULL;
ALTER TABLE movies ALTER COLUMN poster_path DROP NOT NULL;
ALTER TABLE movies ALTER COLUMN backdrop_path DROP NOT NULL;
ALTER TABLE movies ALTER COLUMN release_date DROP NOT NULL;
ALTER TABLE movies ALTER COLUMN vote_average DROP NOT NULL;
ALTER TABLE movies ALTER COLUMN category DROP NOT NULL;

-- Add slug and search_vector to movies
ALTER TABLE movies ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS search_vector tsvector;

-- Make columns robust in tv_series
ALTER TABLE tv_series ALTER COLUMN title SET DEFAULT 'Untitled';
ALTER TABLE tv_series ALTER COLUMN overview DROP NOT NULL;
ALTER TABLE tv_series ALTER COLUMN poster_path DROP NOT NULL;
ALTER TABLE tv_series ALTER COLUMN backdrop_path DROP NOT NULL;
ALTER TABLE tv_series ALTER COLUMN first_air_date DROP NOT NULL;
ALTER TABLE tv_series ALTER COLUMN vote_average DROP NOT NULL;
ALTER TABLE tv_series ALTER COLUMN category DROP NOT NULL;

-- Add slug and search_vector to tv_series
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE tv_series ADD COLUMN IF NOT EXISTS search_vector tsvector;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_movies_slug ON movies(slug);
CREATE INDEX IF NOT EXISTS idx_tv_series_slug ON tv_series(slug);
CREATE INDEX IF NOT EXISTS idx_movies_search ON movies USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS idx_tv_series_search ON tv_series USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS idx_movies_title_trgm ON movies USING GIN(title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_tv_series_title_trgm ON tv_series USING GIN(title gin_trgm_ops);

-- Function to update search_vector automatically
CREATE OR REPLACE FUNCTION movies_search_vector_update() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('arabic', COALESCE(NEW.arabic_title, '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(NEW.overview, '')), 'C');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER movies_search_vector_update
BEFORE INSERT OR UPDATE ON movies
FOR EACH ROW EXECUTE FUNCTION movies_search_vector_update();

CREATE OR REPLACE FUNCTION tv_search_vector_update() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('arabic', COALESCE(NEW.arabic_title, '')), 'A') ||
    setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(NEW.overview, '')), 'C');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER tv_search_vector_update
BEFORE INSERT OR UPDATE ON tv_series
FOR EACH ROW EXECUTE FUNCTION tv_search_vector_update();
