-- Create requests table
CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  notes TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Enable RLS
ALTER TABLE requests ENABLE ROW LEVEL SECURITY;

-- Allow public insert (with rate limiting handled by app logic if needed, or just open for now)
CREATE POLICY "Allow public insert to requests" ON requests FOR INSERT WITH CHECK (true);

-- Allow admins to view/update
-- Assuming admins have role 'admin' in profiles or checked via app logic. 
-- For simplicity here, we allow public insert, and select only for service_role or admin (implementation detail: usually authenticated users can see their own, but this is a simple request system).
-- Let's stick to: Everyone can insert. Only admins (via dashboard) or owner can select.

CREATE POLICY "Allow users to see their own requests" ON requests FOR SELECT USING (auth.uid() = user_id);
