-- Create Anime Table
CREATE TABLE IF NOT EXISTS public.anime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    image_url TEXT,
    rating NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    description TEXT,
    trailer_url TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- Create Quran Reciters Table
CREATE TABLE IF NOT EXISTS public.quran_reciters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT,
    rewaya TEXT,
    server TEXT,
    category TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.anime ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_reciters ENABLE ROW LEVEL SECURITY;

-- Create Policies (Public Read)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'anime' AND policyname = 'Enable read access for all users'
    ) THEN
        CREATE POLICY "Enable read access for all users" ON public.anime FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'quran_reciters' AND policyname = 'Enable read access for all users'
    ) THEN
        CREATE POLICY "Enable read access for all users" ON public.quran_reciters FOR SELECT USING (true);
    END IF;
END
$$;

-- Fix Games Table ID
DO $$
BEGIN
    -- Check if games.id has a default value
    IF (SELECT column_default FROM information_schema.columns WHERE table_name = 'games' AND column_name = 'id') IS NULL THEN
        CREATE SEQUENCE IF NOT EXISTS games_id_seq OWNED BY public.games.id;
        ALTER TABLE public.games ALTER COLUMN id SET DEFAULT nextval('games_id_seq');
        PERFORM setval('games_id_seq', COALESCE((SELECT MAX(id) FROM public.games), 0) + 1, false);
    END IF;
END
$$;

-- Fix Software Table ID
DO $$
BEGIN
    -- Check if software.id has a default value
    IF (SELECT column_default FROM information_schema.columns WHERE table_name = 'software' AND column_name = 'id') IS NULL THEN
        CREATE SEQUENCE IF NOT EXISTS software_id_seq OWNED BY public.software.id;
        ALTER TABLE public.software ALTER COLUMN id SET DEFAULT nextval('software_id_seq');
        PERFORM setval('software_id_seq', COALESCE((SELECT MAX(id) FROM public.software), 0) + 1, false);
    END IF;
END
$$;

-- Insert Seed Data for Anime
INSERT INTO public.anime (title, category, image_url, rating, description) VALUES
('Attack on Titan', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hTP1DtLGFamjfu8WqjnuQdPuy61.jpg', 9.1, 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.'),
('One Piece', 'Adventure', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/cMD9Ygz11zjJzAovURpO75Pg738.jpg', 8.9, 'Monkey D. Luffy refuses to let anyone or anything stand in the way of his quest to become the king of all pirates.'),
('Demon Slayer: Kimetsu no Yaiba', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/xUfRZu2mi8bZJKSe15TLkQymxCot.jpg', 8.8, 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon.'),
('Death Note', 'Thriller', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/tCzeDfOdqB8m0J82s27HCV84xM9.jpg', 9.0, 'Light Yagami is an ace student with great prospects—and he''s bored out of his mind. But all that changes when he finds the Death Note.'),
('Naruto', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vauCEnR7CjyqePGUkyKAoExO75C.jpg', 8.5, 'Naruto Uzumaki, a hyperactive and knuckle-headed ninja, searches for recognition from everyone around him.'),
('Fullmetal Alchemist: Brotherhood', 'Adventure', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5TQ6YAeHHxMcpVNHl1bZ8Zq7e6R.jpg', 9.2, 'Two brothers search for a Philosopher''s Stone after an attempt to revive their deceased mother goes wrong and leaves them in damaged physical forms.'),
('Hunter x Hunter', 'Adventure', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ucmpL591Q07b8l4P7F9vW7x8b4o.jpg', 9.0, 'Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness.'),
('Jujutsu Kaisen', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hITg904yFXn0VvR9g8b9Z8k9j9.jpg', 8.7, 'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life.'),
('My Hero Academia', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/phuYuzqWW9ru8OA3mNdUyXNfdh.jpg', 8.6, 'A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.'),
('Bleach', 'Action', 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2EewMxXe72ogD0Ea18exjE7P0af.jpg', 8.4, 'High school student Ichigo Kurosaki, who has the ability to see ghosts, gains soul reaper powers.');

-- Insert Seed Data for Quran Reciters
INSERT INTO public.quran_reciters (name, image, rewaya, server, category) VALUES
('Mishary Rashid Alafasy', 'https://upload.wikimedia.org/wikipedia/commons/2/29/Mishary_Rashid_Al-Afasy.jpg', 'Hafs', 'https://server8.mp3quran.net/afs/', 'Famous'),
('Maher Al Muaiqly', 'https://i1.sndcdn.com/artworks-000236613390-2p0a6v-t500x500.jpg', 'Hafs', 'https://server12.mp3quran.net/maher/', 'Famous'),
('Abdul Rahman Al-Sudais', 'https://static.surahquran.com/images/reciters/1.jpg', 'Hafs', 'https://server11.mp3quran.net/sds/', 'Famous'),
('Saad Al Ghamdi', 'https://static.surahquran.com/images/reciters/4.jpg', 'Hafs', 'https://server7.mp3quran.net/s_gmd/', 'Famous'),
('Yasser Al-Dosari', 'https://static.surahquran.com/images/reciters/2.jpg', 'Hafs', 'https://server11.mp3quran.net/yasser/', 'Famous'),
('Ahmed Al-Ajmi', 'https://static.surahquran.com/images/reciters/3.jpg', 'Hafs', 'https://server10.mp3quran.net/ajm/', 'Famous'),
('Saud Al-Shuraim', 'https://static.surahquran.com/images/reciters/6.jpg', 'Hafs', 'https://server7.mp3quran.net/shur/', 'Famous'),
('Fares Abbad', 'https://static.surahquran.com/images/reciters/8.jpg', 'Hafs', 'https://server8.mp3quran.net/frs_a/', 'Famous'),
('Nasser Al Qatami', 'https://static.surahquran.com/images/reciters/16.jpg', 'Hafs', 'https://server6.mp3quran.net/qtm/', 'Famous'),
('Idris Abkar', 'https://static.surahquran.com/images/reciters/19.jpg', 'Hafs', 'https://server6.mp3quran.net/abkr/', 'Famous');

-- Insert Seed Data for Games (if empty)
INSERT INTO public.games (title, category, poster_url, rating, release_year, description) 
SELECT 'Grand Theft Auto V', 'Console', 'https://media.rawg.io/media/games/456/456dea5e127e3d7770975f19475e3c92.jpg', 9.5, 2013, 'Open world action-adventure game.'
WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE title = 'Grand Theft Auto V');

INSERT INTO public.games (title, category, poster_url, rating, release_year, description) 
SELECT 'The Witcher 3: Wild Hunt', 'PC', 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg', 9.8, 2015, 'Action role-playing game.'
WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE title = 'The Witcher 3: Wild Hunt');

INSERT INTO public.games (title, category, poster_url, rating, release_year, description) 
SELECT 'Red Dead Redemption 2', 'Console', 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg', 9.7, 2018, 'Western action-adventure game.'
WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE title = 'Red Dead Redemption 2');

INSERT INTO public.games (title, category, poster_url, rating, release_year, description) 
SELECT 'Cyberpunk 2077', 'PC', 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a60f0a5652.jpg', 8.5, 2020, 'Open world action-adventure story.'
WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE title = 'Cyberpunk 2077');

INSERT INTO public.games (title, category, poster_url, rating, release_year, description) 
SELECT 'God of War', 'Console', 'https://media.rawg.io/media/games/4be/4be6a6ad0364751a96229c56bf69be59.jpg', 9.8, 2018, 'Action-adventure game based on Norse mythology.'
WHERE NOT EXISTS (SELECT 1 FROM public.games WHERE title = 'God of War');

-- Insert Seed Data for Software (if empty)
INSERT INTO public.software (title, category, poster_url, rating, release_year, description) 
SELECT 'Adobe Photoshop 2024', 'PC', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Adobe_Photoshop_CC_icon.svg/1200px-Adobe_Photoshop_CC_icon.svg.png', 9.5, 2024, 'Professional image editing software.'
WHERE NOT EXISTS (SELECT 1 FROM public.software WHERE title = 'Adobe Photoshop 2024');

INSERT INTO public.software (title, category, poster_url, rating, release_year, description) 
SELECT 'Visual Studio Code', 'PC', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png', 9.9, 2024, 'Code editor redefined.'
WHERE NOT EXISTS (SELECT 1 FROM public.software WHERE title = 'Visual Studio Code');

INSERT INTO public.software (title, category, poster_url, rating, release_year, description) 
SELECT 'Microsoft Office 2021', 'PC', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Microsoft_Office_logo_%282019%E2%80%93present%29.svg/1200px-Microsoft_Office_logo_%282019%E2%80%93present%29.svg.png', 9.0, 2021, 'Productivity suite.'
WHERE NOT EXISTS (SELECT 1 FROM public.software WHERE title = 'Microsoft Office 2021');

INSERT INTO public.software (title, category, poster_url, rating, release_year, description) 
SELECT 'Premiere Pro 2024', 'PC', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Adobe_Premiere_Pro_CC_icon.svg/1200px-Adobe_Premiere_Pro_CC_icon.svg.png', 9.2, 2024, 'Video editing software.'
WHERE NOT EXISTS (SELECT 1 FROM public.software WHERE title = 'Premiere Pro 2024');
