-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Movies Table
create table if not exists movies (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  poster_url text,
  banner_url text,
  video_url text,
  category text,
  year int,
  release_date date,
  rating numeric,
  views int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tmdb_id int
);

-- 2. Series Table
create table if not exists series (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  poster_url text,
  banner_url text,
  first_air_date date,
  rating numeric,
  views int default 0,
  seasons_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tmdb_id int
);

-- 3. Seasons Table
create table if not exists seasons (
  id bigint generated by default as identity primary key,
  series_id bigint references series(id) on delete cascade not null,
  name text,
  season_number int not null,
  episode_count int default 0,
  poster_url text,
  air_date date,
  overview text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Episodes Table
create table if not exists episodes (
  id bigint generated by default as identity primary key,
  series_id bigint references series(id) on delete cascade not null,
  season_id bigint references seasons(id) on delete cascade not null,
  title text not null,
  episode_number int not null,
  overview text,
  still_url text,
  air_date date,
  rating numeric,
  runtime int,
  video_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Profiles Table
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text,
  role text check (role in ('user', 'admin', 'supervisor')) default 'user',
  banned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Buckets
insert into storage.buckets (id, name, public) 
values ('posters', 'posters', true)
on conflict (id) do nothing;

-- RLS Policies
alter table movies enable row level security;
alter table series enable row level security;
alter table seasons enable row level security;
alter table episodes enable row level security;
alter table profiles enable row level security;

-- Drop existing policies to ensure idempotency
drop policy if exists "Public movies are viewable by everyone" on movies;
drop policy if exists "Authenticated users can insert movies" on movies;
drop policy if exists "Authenticated users can update movies" on movies;
drop policy if exists "Authenticated users can delete movies" on movies;

drop policy if exists "Public series are viewable by everyone" on series;
drop policy if exists "Authenticated users can insert series" on series;
drop policy if exists "Authenticated users can update series" on series;
drop policy if exists "Authenticated users can delete series" on series;

drop policy if exists "Public seasons are viewable by everyone" on seasons;
drop policy if exists "Authenticated users can insert seasons" on seasons;
drop policy if exists "Authenticated users can update seasons" on seasons;
drop policy if exists "Authenticated users can delete seasons" on seasons;

drop policy if exists "Public episodes are viewable by everyone" on episodes;
drop policy if exists "Authenticated users can insert episodes" on episodes;
drop policy if exists "Authenticated users can update episodes" on episodes;
drop policy if exists "Authenticated users can delete episodes" on episodes;

drop policy if exists "Public profiles are viewable by everyone" on profiles;

drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Authenticated users can upload" on storage.objects;

-- Create Policies

-- Movies
create policy "Public movies are viewable by everyone" on movies for select using (true);
create policy "Authenticated users can insert movies" on movies for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update movies" on movies for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete movies" on movies for delete using (auth.role() = 'authenticated');

-- Series
create policy "Public series are viewable by everyone" on series for select using (true);
create policy "Authenticated users can insert series" on series for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update series" on series for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete series" on series for delete using (auth.role() = 'authenticated');

-- Seasons
create policy "Public seasons are viewable by everyone" on seasons for select using (true);
create policy "Authenticated users can insert seasons" on seasons for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update seasons" on seasons for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete seasons" on seasons for delete using (auth.role() = 'authenticated');

-- Episodes
create policy "Public episodes are viewable by everyone" on episodes for select using (true);
create policy "Authenticated users can insert episodes" on episodes for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update episodes" on episodes for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete episodes" on episodes for delete using (auth.role() = 'authenticated');

-- Profiles
create policy "Public profiles are viewable by everyone" on profiles for select using (true);

-- Storage
create policy "Public Access" on storage.objects for select using ( bucket_id = 'posters' );
create policy "Authenticated users can upload" on storage.objects for insert with check ( bucket_id = 'posters' and auth.role() = 'authenticated' );
